export const DOWNLOAD_CHALLENGES = 'DOWNLOAD_CHALLENGES';
export const DOWNLOAD_CHALLENGES_COMPLETE = 'DOWNLOAD_CHALLENGES_COMPLETE';
export const DOWNLOAD_CHALLENGES_ERROR = 'DOWNLOAD_CHALLENGES_ERROR';

export const MARK_CHALLENGE_SELECTED = 'MARK_CHALLENGE_SELECTED';
export const UPDATE_CHALLENGE_SELECTED = 'UPDATE_CHALLENGE_SELECTED';